---
site_name: DevOps Docs
site_description: Documentations autour de la CI/CD et de Github
site_url: http://localhost
site_author: Aurelien

repo_name: profy12-mon-orga/doc
repo_url: https://github.com/profy12-mon-orga/doc

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: 'fr'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

nav:
  - Accueil: /
  - Github:
      - Gestion de compte: github/account.md
      - Les hooks git: github/git-hooks.md
      - Introduction à Github Action: github/ga-intro.md
      - Le local runner: github/ga-local-runner.md

markdown_extensions:
  #- mdx_truly_sane_lists # for mkdocs to indent nested lists with 2 spaces VS 4 by default
  #- pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.magiclink
  #- pymdownx.saneheaders
  - pymdownx.smartsymbols
  #- footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
plugins:
  - tags
  - search:
      prebuild_index: false
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - _assets/stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _assets/javascript/tables.js
