---
name: Cowsay Workflow

on:
  push:
    branches:
      - main

jobs:
  cowsay-job:
    runs-on: ubuntu-latest

    steps:
      # Étape pour afficher une vache avec cowsay
      - name: Cowsay Hello
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
          cowsay "Hello from GitHub Actions!"