---
name: Cowsay Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version you shoud want'
        required: true
        type: string
        default: "0.1"
  push:
    branches:
      - main

jobs:
  cowsay-job:
    runs-on: ubuntu-latest

    steps:
      # Étape pour afficher une vache avec cowsay
      - name: Cowsay Hello
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
          cowsay "Hello from GitHub Actions! La version est $VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}